### ISSUE TITLE
Please help me understand why is GPL3 library used in proprietary software WhatsApp?

### ISSUE THREAD

**Issue by 717g301github** [signalapp/libsignal-protocol-java#42]
Please help me understand why is GPL3 library used in proprietary software WhatsApp?

According to Wikipedia: WhatsApp calls are encrypted with SRTP, and all client-server communications are "layered within a separate encrypted channel".[124] The Signal Protocol library used by WhatsApp is open-source and published under the GPLv3 license.[124][125]

References to 124: https://www.whatsapp.com/security/WhatsApp-Security-Whitepaper.pdf where it says how they are using this library is open source:

The Signal Protocol library used by WhatsApp is Open Source, available
here: https://github.com/whispersystems/libsignal-protocol-java/

To what degree the hypocrisy may go?

Is the Whatsapp proprietary? 

And why are you allowing them to use the GPL 3 licensed software?

If they did use the software with the GPL 3 licensed software, now their Whatsapp is automatically to release their source code, as they are bound to GPL 3 license.

And what are you doing there? Nothing?

**Comment by moxie0** [comment]
Sorry but we don't use GH issues for questions or discussion.
