### ISSUE TITLE
Conflict when using android libraries with protobuf-lite dependency

### ISSUE THREAD

**Issue by abdularis** [signalapp/libsignal-protocol-java#52]
When you use any libraries which has dependency to protobuf-lite it would not compile because you need to either use protobuf-java or protobuf-lite.
protobuf-lite is the recommended one for android.
Thank you.

**Comment by FahimDsi** [comment]
Try this
implementation ('org.whispersystems:signal-protocol-android:version'){
        exclude group: 'com.google.protobuf', module:'protobuf-java'
    }

**Comment by abdularis** [comment]
I ended up forking and modify it to use protobuf-lite version, I'll try your solution by excluding the dependency and see if it works, Thanks

**Comment by harishvishwakarma** [comment]
Hey @abdularis , can you share that modded fork please? Would help me a lot. Stuck with the same issue.

**Comment by abdularis** [comment]
maybe you can try @FahimDsi solution, I have not pushed the changed to github, but you can change the protobuf dependency of this library in the java module to use protobuf-lite version, build then export the library as maven repository so you can include it inside your project

**Comment by harishvishwakarma** [comment]
> maybe you can try @FahimDsi solution

I have tried @FahimDsi solution but it causes missing classes in the project.

>  I have not pushed the changed to github, but you can change the protobuf dependency of this library in the java module to use protobuf-lite version, build then export the library as maven repository so you can include it inside your project

I have tried this too, but there are many missing classes in the protobuf-lite lib.
Some of those are in the attached image. How did you go about resolving those?

<img width="607" alt="Screenshot 2019-10-09 at 1 46 20 PM" src="https://user-images.githubusercontent.com/5672275/66463716-4631a580-ea9b-11e9-98a4-50004f9d4ea5.png">

**Comment by harishvishwakarma** [comment]
@abdularis and whoever else might need it. I was able to compile the Signal java library with Protobuf Lite. 

https://github.com/harishvishwakarma/libsignal-protocol-java

You can create Jar by running assemble.

**Comment by abdularis** [comment]
Cool, I actually just push the code

**Comment by abdularis** [comment]
I'm writing an article about signal protocol but I haven't completed yet, maybe you wanna share

https://github.com/abdularis/learn-signal-protocol

**Comment by harishvishwakarma** [comment]
@abdularis Thanks mate. My repo seems incomplete now that I am finally trying to use the jar. Will try your changes. Thanks

**Comment by alan-signal** [comment]
We recently updated to protobuf 3.10 lite.
