### ISSUE TITLE
What does "install time" mean?

### ISSUE THREAD

**Issue by bfamzz** [signalapp/libsignal-protocol-java#66]
Hello. 

I am trying to understand what "install time" means in the following statement from the READMe page.

> At install time, a libsignal client needs to generate its identity keys, registration id, and prekeys.

Does it mean that when the app is installing, the keys will be generated? If yes, how do can I write install code?

Or, does it mean that generating the keys should be the first thing the app does when installed on a device?

Thanks.

**Comment by alan-signal** [comment]
Please use the community forum for questions around development https://community.signalusers.org/
