### ISSUE TITLE
KeyHelper.generateIdentityKeyPair() throws exception while proguard is enabled

### ISSUE THREAD

**Issue by malik082009** [signalapp/libsignal-protocol-java#74]
`KeyHelper.generateIdentityKeyPair()` throws `k.c.a.d `exception

```
    debug {
            minifyEnabled true   // Obfuscate and minify codes
            shrinkResources true // Remove unused resources
            useProguard true
            debuggable true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
```

**Comment by sharpstar2000** [comment]
> `KeyHelper.generateIdentityKeyPair()` throws `k.c.a.d `exception
> 
> 
> 
> ```
> 
>     debug {
> 
>             minifyEnabled true   // Obfuscate and minify codes
> 
>             shrinkResources true // Remove unused resources
> 
>             useProguard true
> 
>             debuggable true
> 
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
> 
>         }
> 
> ```
> 
>

**Comment by malik082009** [comment]
> `KeyHelper.generateIdentityKeyPair()` throws `k.c.a.d `exception
> 
> ```
>     debug {
>             minifyEnabled true   // Obfuscate and minify codes
>             shrinkResources true // Remove unused resources
>             useProguard true
>             debuggable true
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
> ```
adding 
```
-dontoptimize
-dontobfuscate
-keepattributes SourceFile,LineNumberTable
-keep class org.whispersystems.** { *; }
-keep class org.thoughtcrime.securesms.** { *; }
-keepclassmembers class ** {
    public void onEvent*(**);

```
in `progaurd-rules.pro` resolved the issue.
